# Generated by Django 5.2.12 on 2026-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('product_manager', 'Product Manager'), ('order_manager', 'Order Manager'), ('customer_support', 'Customer Support')], default='customer', max_length=20),
        ),
    ]
