"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Đọc .env: ưu tiên backend/.env; nếu thiếu biến có thể bổ sung từ .env ở thư mục gốc repo
_repo_root = BASE_DIR.parent
load_dotenv(_repo_root / '.env', override=False)
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$l_a$sg4yn*5bbk2k2ut!pqjm_pn(e&2f4n$1b&o9!9o-idl18'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',

    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',

    'accounts',
    'products',
    'cart',
    'orders',
    'reviews',
    'contact',
    'core',
    'wishlist',
    'payments',
    'wallets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Mặc định SQLite để chạy local không cần Postgres; production dùng .env (PostgreSQL).
_db_engine = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')

if _db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('DB_NAME', 'nt4'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', '123456'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# React dev server (Vite) default: http://localhost:5173 — dùng cho CORS và link đặt lại mật khẩu trong email
FRONTEND_ORIGIN = os.getenv('FRONTEND_ORIGIN', 'http://localhost:5173').rstrip('/')

CORS_ALLOWED_ORIGINS = [
    FRONTEND_ORIGIN,
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

# JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
# Gmail App Password hay dán kèm dấu cách "xxxx xxxx ..." — SMTP cần 16 ký tự liền
EMAIL_HOST_USER = (os.getenv('EMAIL_HOST_USER', '') or '').strip()
EMAIL_HOST_PASSWORD = ''.join((os.getenv('EMAIL_HOST_PASSWORD', '') or '').split())
# Gmail thường yêu cầu From trùng tài khoản gửi — nếu .env để trống thì dùng EMAIL_HOST_USER
_default_from = (os.getenv('DEFAULT_FROM_EMAIL') or '').strip()
DEFAULT_FROM_EMAIL = _default_from or EMAIL_HOST_USER or 'noreply@fashionstore.com'

# Email templates
EMAIL_TEMPLATE_DIR = BASE_DIR / 'templates' / 'emails'

# Gửi email xác nhận đơn sau checkout (cần cấu hình SMTP trong .env)
ORDER_CONFIRMATION_EMAIL_ENABLED = os.getenv('ORDER_CONFIRMATION_EMAIL_ENABLED', '1').lower() in (
    '1',
    'true',
    'yes',
)

# Email khi đơn chuyển sang đang giao (staff PATCH status -> shipping)
ORDER_SHIPPED_EMAIL_ENABLED = os.getenv('ORDER_SHIPPED_EMAIL_ENABLED', '1').lower() in (
    '1',
    'true',
    'yes',
)

# Email khi staff hoàn tất yêu cầu trả hàng (ReturnRequest complete)
RETURN_REFUND_EMAIL_ENABLED = os.getenv('RETURN_REFUND_EMAIL_ENABLED', '1').lower() in (
    '1',
    'true',
    'yes',
)

# Email nhắc sinh nhật (gửi trước 1 ngày) — chạy: python manage.py send_birthday_reminders (cron mỗi ngày)
BIRTHDAY_REMINDER_EMAIL_ENABLED = os.getenv('BIRTHDAY_REMINDER_EMAIL_ENABLED', '1').lower() in (
    '1',
    'true',
    'yes',
)
# Mã voucher hiển thị trong email (tuỳ chọn; để trống = chỉ lời chúc / CTA shop)
BIRTHDAY_VOUCHER_CODE = (os.getenv('BIRTHDAY_VOUCHER_CODE') or '').strip()

# Google OAuth2 Configuration
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
# Mặc định theo FRONTEND_ORIGIN — trùng với Vite `${origin}/auth/google/callback`
GOOGLE_REDIRECT_URI = os.getenv(
    'GOOGLE_REDIRECT_URI',
    f'{FRONTEND_ORIGIN}/auth/google/callback',
)

# Facebook OAuth Configuration
# DEBUG: nếu chưa có trong .env, dùng cùng App ID mặc định như frontend (Login.tsx / VITE_FACEBOOK_APP_ID)
FACEBOOK_APP_ID = (os.getenv('FACEBOOK_APP_ID') or '').strip() or (
    '918507394342467' if DEBUG else None
)
# Bỏ khoảng trắng đầu/cuối (lỗi thường gặp khi copy từ Meta)
FACEBOOK_APP_SECRET = (os.getenv('FACEBOOK_APP_SECRET') or '').strip() or None
FACEBOOK_REDIRECT_URI = os.getenv(
    'FACEBOOK_REDIRECT_URI',
    f'{FRONTEND_ORIGIN}/auth/facebook/callback',
)

# Public URL của backend (dùng cho VNPay/MoMo return & IPN). Local: http://127.0.0.1:8000
BACKEND_PUBLIC_BASE = (os.getenv('BACKEND_PUBLIC_BASE') or '').strip().rstrip('/')

# VNPay — https://sandbox.vnpayment.vn/ (sandbox) hoặc production URL; IPN cần URL công khai (ngrok) giống MoMo
VNP_TMN_CODE = (os.getenv('VNP_TMN_CODE') or '').strip()
VNP_HASH_SECRET = (os.getenv('VNP_HASH_SECRET') or '').strip()
VNP_PAYMENT_URL = (os.getenv('VNP_PAYMENT_URL') or '').strip() or 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'
VNP_RETURN_PATH = os.getenv('VNP_RETURN_PATH', '/api/payments/vnpay/return/')
VNP_IPN_PATH = os.getenv('VNP_IPN_PATH', '/api/payments/vnpay/ipn/')
try:
    _vnp_exp = int((os.getenv('VNP_EXPIRE_MINUTES') or '30').strip())
except ValueError:
    _vnp_exp = 30
VNP_EXPIRE_MINUTES = max(5, min(_vnp_exp, 180))
# Thanh toán QR VNPAY-QR (quét app ngân hàng); để trống = khách chọn trên cổng — xem tài liệu vnp_BankCode
VNP_BANK_CODE = (os.getenv('VNP_BANK_CODE') or '').strip()
VNP_API_URL = (os.getenv('VNP_API_URL') or '').strip() or 'https://sandbox.vnpayment.vn/merchant_webapi/api/transaction'
# True = gửi vnp_ExpireDate (tài liệu mới); False = giống vnpay_python.zip — tránh lệch checksum sandbox/demo
VNP_SEND_EXPIRE_DATE = os.getenv('VNP_SEND_EXPIRE_DATE', 'false').lower() in ('1', 'true', 'yes', 'on')

# MoMo — https://developers.momo.vn/ (test endpoint mặc định)
# Dev: đặt MOMO_* sandbox trong .env; BACKEND_PUBLIC_BASE=http://127.0.0.1:8000 khi frontend Vite proxy /api.
# IPN từ MoMo không tới được localhost — chỉ return trình duyệt hoạt động; test IPN đầy đủ cần ngrok + BACKEND_PUBLIC_BASE https.
MOMO_PARTNER_CODE = (os.getenv('MOMO_PARTNER_CODE') or '').strip()
MOMO_ACCESS_KEY = (os.getenv('MOMO_ACCESS_KEY') or '').strip()
MOMO_SECRET_KEY = (os.getenv('MOMO_SECRET_KEY') or '').strip()
MOMO_PARTNER_NAME = os.getenv('MOMO_PARTNER_NAME', 'FashionStore')
MOMO_STORE_ID = os.getenv('MOMO_STORE_ID', 'FashionStore')
MOMO_ENDPOINT = (os.getenv('MOMO_ENDPOINT') or '').strip() or 'https://test-payment.momo.vn/v2/gateway/api/create'
MOMO_RETURN_PATH = os.getenv('MOMO_RETURN_PATH', '/api/payments/momo/return/')
MOMO_IPN_PATH = os.getenv('MOMO_IPN_PATH', '/api/payments/momo/notify/')
# payWithMethod = collection link (chọn phương thức trên MoMo); captureWallet = ví MoMo trực tiếp
MOMO_REQUEST_TYPE = (os.getenv('MOMO_REQUEST_TYPE') or 'payWithMethod').strip()
MOMO_AUTO_CAPTURE = os.getenv('MOMO_AUTO_CAPTURE', 'true').lower() in ('1', 'true', 'yes', 'on')
MOMO_ORDER_GROUP_ID = (os.getenv('MOMO_ORDER_GROUP_ID') or '').strip()

# ZaloPay — https://docs.zalopay.vn/ (sandbox: sb-openapi.zalopay.vn). Callback cần URL công khai (ngrok) + BACKEND_PUBLIC_BASE https.
ZALOPAY_APP_ID = (os.getenv('ZALOPAY_APP_ID') or '').strip()
ZALOPAY_KEY1 = (os.getenv('ZALOPAY_KEY1') or '').strip()
ZALOPAY_KEY2 = (os.getenv('ZALOPAY_KEY2') or '').strip()
ZALOPAY_CREATE_ENDPOINT = (os.getenv('ZALOPAY_CREATE_ENDPOINT') or '').strip() or (
    'https://sb-openapi.zalopay.vn/v2/create'
)
ZALOPAY_QUERY_ENDPOINT = (os.getenv('ZALOPAY_QUERY_ENDPOINT') or '').strip() or (
    'https://sb-openapi.zalopay.vn/v2/query'
)
ZALOPAY_CALLBACK_PATH = os.getenv('ZALOPAY_CALLBACK_PATH', '/api/payments/zalopay/callback/')
