services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: nt4
    ports:
      - "5432:5432"
    volumes:
      - fashionstore_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nt4"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fashionstore_net

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - fashionstore_net

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - fashionstore_net

networks:
  fashionstore_net:
    driver: bridge

volumes:
  fashionstore_pgdata:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs: