sonar.projectKey=fashionstore
sonar.projectName=FashionStore
sonar.projectVersion=1.0

# Trỏ vào IP máy của người host SonarQube
# Ví dụ: http://192.168.1.10:9000
sonar.host.url=http://100.114.69.7:9000

sonar.sources=backend   
sonar.inclusions=**/*.py
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.projectBaseDir=.

sonar.exclusions=\
    backend/.venv/**,\
    backend/**/migrations/**,\
    backend/**/__pycache__/**,\
    backend/media/**,\
    backend/templates/**,\
    backend/data.json,\
    backend/wallet_test.json,\
    frontend/**,\
    backend/**/tests.py,\
    backend/**/test_*.py,\
    backend/admin_tests.py

sonar.coverage.exclusions=\
    backend/**/migrations/**,\
    backend/**/tests.py,\
    backend/**/test_*.py,\
    backend/admin_tests.py,\
    backend/manage.py,\
    backend/api/wsgi.py,\
    backend/api/asgi.py,\
    backend/accounts/birthday_reminder.py,\
    backend/products/management/**,\
    backend/products/management/seed_ecommerce.py,\
    backend/products/management/audit_order_schema.py,\