sonar.projectKey=fashionstore
sonar.projectName=FashionStore
sonar.projectVersion=1.0

# Đổi localhost → tên service trong docker-compose
sonar.host.url=http://sonarqube:9000
sonar.token=${SONAR_TOKEN}

sonar.sources=.

sonar.python.version=3.13
sonar.sourceEncoding=UTF-8