sonar.projectKey=fashionstore
sonar.projectName=FashionStore
sonar.projectVersion=1.0

# Trỏ vào IP máy của người host SonarQube
# Ví dụ: http://192.168.1.10:9000
sonar.host.url=http://100.112.137.19:9000
sonar.token=${SONAR_TOKEN}

sonar.sources=.
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=backend/coverage.xml