# Generated by Django 5.2.12 on 2026-04-03 18:51

from django.db import migrations, models


def backfill_order_subtotals(apps, schema_editor):
    """Đơn cũ: không tách subtotal/phí ship — gán subtotal = total_price, phí ship = 0."""
    Order = apps.get_model("orders", "Order")
    for o in Order.objects.all().iterator():
        o.subtotal = o.total_price
        o.shipping_fee = 0
        o.save(update_fields=["subtotal", "shipping_fee"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Phí vận chuyển (VNĐ)', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tạm tính (hàng), tính trên server', max_digits=12),
        ),
        migrations.AddField(
            model_name='shipping',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(backfill_order_subtotals, migrations.RunPython.noop),
    ]
