# Generated by Django 6.0.3 on 2026-04-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
