# Generated by Django 6.0.3 on 2026-04-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_gateway_txn_and_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='inventory_deducted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipping', 'Shipping'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('returning', 'Returning'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
    ]
