# Generated by Django 5.2.12 on 2026-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_updated_at_alter_order_inventory_deducted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, default='', help_text='Mã giao dịch cổng (VNPay / MoMo / ZaloPay)', max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('vnpay', 'VNPay'), ('momo', 'Ví MoMo'), ('zalopay', 'Ví ZaloPay')], default='cod', max_length=24),
        ),
    ]
