# Generated by Django 5.2.13 on 2026-04-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_zalopay_app_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zalopay_app_trans_id',
            field=models.CharField(blank=True, default='', help_text='app_trans_id gửi ZaloPay (dùng API query khi callback không tới server).', max_length=48),
        ),
    ]
