# Generated by Django 4.2.30 on 2026-04-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_zalopay_app_trans_id'),
        ('orders', '0020_order_payment_method_wallet'),
    ]

    operations = [
    ]
