# Generated by Django 6.0.3 on 2026-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
