# Generated by Django 5.2.12 on 2026-04-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options'),
        ('products', '0005_alter_product_options_productvariant_price'),
    ]

    operations = [
    ]
