# Generated by Django 5.2.13 on 2026-04-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20260416_1728'),
        ('products', '0006_product_rating_product_sold_count'),
    ]

    operations = [
    ]
