# Generated by Django 6.0.3 on 2026-04-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20260418_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='size',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
    ]
