# Generated by Django 6.0.3 on 2026-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_size_options_size_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.ImageField(blank=True, null=True, upload_to='size_charts/', verbose_name='Bảng kích thước'),
        ),
    ]
