# Generated by Django 5.2.12 on 2026-04-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
