# Generated by Django 5.2.13 on 2026-07-01 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Giá sản phẩm phải lớn hơn 0.')]),
        ),
    ]
