# Generated by Django 5.2.13 on 2026-07-01 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='% giảm giá phải lớn hơn 0.'), django.core.validators.MaxValueValidator(100, message='% giảm giá không được vượt quá 100.')]),
        ),
    ]
