# Generated by Django 5.2.12 on 2026-04-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
