# Generated by Django 5.2.12 on 2026-03-22 08:57
#
# Một số DB đã có sẵn cột (ví dụ content) — thêm cột chỉ khi chưa có để tránh DuplicateColumn.

from django.conf import settings
from django.db import migrations, models


def _apply_columns(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                "ALTER TABLE reviews_review ADD COLUMN IF NOT EXISTS content TEXT NOT NULL DEFAULT ''"
            )
            cursor.execute(
                "ALTER TABLE reviews_review ADD COLUMN IF NOT EXISTS feedback_type VARCHAR(20) NOT NULL DEFAULT 'quality'"
            )
            cursor.execute(
                "ALTER TABLE reviews_review ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()"
            )
        return

    if connection.vendor == "sqlite":
        with connection.cursor() as cursor:
            cursor.execute("PRAGMA table_info(reviews_review)")
            cols = {row[1] for row in cursor.fetchall()}
            if "content" not in cols:
                cursor.execute(
                    "ALTER TABLE reviews_review ADD COLUMN content TEXT NOT NULL DEFAULT ''"
                )
            if "feedback_type" not in cols:
                cursor.execute(
                    "ALTER TABLE reviews_review ADD COLUMN feedback_type VARCHAR(20) NOT NULL DEFAULT 'quality'"
                )
            if "updated_at" not in cols:
                cursor.execute(
                    "ALTER TABLE reviews_review ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP"
                )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_color_size_remove_product_image_and_more"),
        ("reviews", "0002_alter_comment_product_alter_review_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="review",
                    name="content",
                    field=models.TextField(blank=True),
                ),
                migrations.AddField(
                    model_name="review",
                    name="feedback_type",
                    field=models.CharField(
                        choices=[
                            ("quality", "Chất lượng sản phẩm"),
                            ("price", "Giá cả"),
                            ("shipping", "Vấn đề giao hàng"),
                            ("size", "Kích thước/Size"),
                            ("service", "Chăm sóc khách hàng"),
                            ("other", "Khác"),
                        ],
                        default="quality",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="review",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AlterField(
                    model_name="review",
                    name="rating",
                    field=models.IntegerField(
                        choices=[
                            (1, "1 sao"),
                            (2, "2 sao"),
                            (3, "3 sao"),
                            (4, "4 sao"),
                            (5, "5 sao"),
                        ]
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="review",
                    unique_together={("user", "product")},
                ),
            ],
            database_operations=[
                migrations.RunPython(_apply_columns, _noop_reverse),
                migrations.AlterField(
                    model_name="review",
                    name="rating",
                    field=models.IntegerField(
                        choices=[
                            (1, "1 sao"),
                            (2, "2 sao"),
                            (3, "3 sao"),
                            (4, "4 sao"),
                            (5, "5 sao"),
                        ]
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="review",
                    unique_together={("user", "product")},
                ),
            ],
        ),
    ]
